services:
  osiris2fhir:
    build: .
    ports:
      - "8080:8080"
    environment:
      FHIR_PROFILE: ${PROJECT:-pscc}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
  blaze:
    image: docker.verbis.dkfz.de/cache/samply/blaze
    environment:
      ENFORCE_REFERENTIAL_INTEGRITY: "false"
    volumes:
      - "blaze-osiris2fhir:/app/data"
volumes:
  blaze-osiris2fhir: